/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

import licencia.CrearLicencia;
import licencia.Licencia;
import licencia.ModificarLicencia;
import licencia.AsignarLicencia;
/**
 *
 * @author jesus
 */
public class MenuLicencia extends javax.swing.JInternalFrame {

    /**
     * Creates new form menuLicencia
     */
    public MenuLicencia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnArticulos = new javax.swing.JButton();
        btnAsignarProfesor = new javax.swing.JButton();
        btnConsultas = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(851, 340));
        setMinimumSize(new java.awt.Dimension(851, 340));
        setPreferredSize(new java.awt.Dimension(851, 340));

        jPanel1.setMaximumSize(new java.awt.Dimension(851, 340));
        jPanel1.setMinimumSize(new java.awt.Dimension(851, 340));
        jPanel1.setPreferredSize(new java.awt.Dimension(851, 340));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnArticulos.setText("Aceptar");
        btnArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArticulosActionPerformed(evt);
            }
        });
        jPanel1.add(btnArticulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        btnAsignarProfesor.setText("Aceptar");
        btnAsignarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarProfesorActionPerformed(evt);
            }
        });
        jPanel1.add(btnAsignarProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 170, -1, -1));

        btnConsultas.setText("Aceptar");
        btnConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultasActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 170, -1, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 270, -1, -1));

        btnModificar.setText("Aceptar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(719, 170, -1, -1));

        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modificar Licencia", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, 170, 80));

        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ver Articulos", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 170, 80));

        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Asignar Profesor", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 170, 80));

        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consultar Licencia", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 170, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArticulosActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
        CrearLicencia crear=new CrearLicencia();
        Principal.panelPrincipal.add(crear);
        crear.setVisible(true);
    }//GEN-LAST:event_btnArticulosActionPerformed

    private void btnAsignarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarProfesorActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        
        AsignarLicencia asignar=new AsignarLicencia();
        Principal.panelPrincipal.add(asignar);
        asignar.setVisible(true);
    }//GEN-LAST:event_btnAsignarProfesorActionPerformed

    private void btnConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
        Licencia art=new Licencia();
        Principal.panelPrincipal.add(art);
        art.setVisible(true);
    }//GEN-LAST:event_btnConsultasActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
        ModificarLicencia modificar=new ModificarLicencia();
        Principal.panelPrincipal.add(modificar);
        modificar.setVisible(true);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
         Principal.activarPanel();
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArticulos;
    private javax.swing.JButton btnAsignarProfesor;
    private javax.swing.JButton btnConsultas;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
