/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

/**
 *
 * @author jesus
 */
public class MenuListado extends javax.swing.JInternalFrame {

    /**
     * Creates new form menuListado
     */
    public MenuListado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnListadoPorCurso = new javax.swing.JButton();
        btnListadoPorCicloLectivo = new javax.swing.JButton();
        btnListadoDeEgresado = new javax.swing.JButton();
        btnListadoDeudores = new javax.swing.JButton();
        btnListadoAbandono = new javax.swing.JButton();
        btnListadoGeneral = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(780, 380));
        setMinimumSize(new java.awt.Dimension(780, 380));
        setPreferredSize(new java.awt.Dimension(780, 380));

        jPanel1.setMaximumSize(new java.awt.Dimension(780, 380));
        jPanel1.setMinimumSize(new java.awt.Dimension(780, 380));
        jPanel1.setPreferredSize(new java.awt.Dimension(780, 380));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnListadoPorCurso.setText("Aceptar");
        jPanel1.add(btnListadoPorCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 104, -1, -1));

        btnListadoPorCicloLectivo.setText("Aceptar");
        jPanel1.add(btnListadoPorCicloLectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 104, -1, -1));

        btnListadoDeEgresado.setText("Aceptar");
        jPanel1.add(btnListadoDeEgresado, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 104, -1, -1));

        btnListadoDeudores.setText("Aceptar");
        jPanel1.add(btnListadoDeudores, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 236, -1, -1));

        btnListadoAbandono.setText("Aceptar");
        jPanel1.add(btnListadoAbandono, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 236, -1, -1));

        btnListadoGeneral.setText("Aceptar");
        jPanel1.add(btnListadoGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 236, -1, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, -1, -1));

        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado General", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 170, 80));

        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado por Curso", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 170, 80));

        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado por Ciclo Lectivo", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 170, 80));

        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado de Egresado", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 170, 80));

        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado de Deudores", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 170, 80));

        jLabel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado de  Desercion", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 170, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
         Principal.activarPanel();
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListadoAbandono;
    private javax.swing.JButton btnListadoDeEgresado;
    private javax.swing.JButton btnListadoDeudores;
    private javax.swing.JButton btnListadoGeneral;
    private javax.swing.JButton btnListadoPorCicloLectivo;
    private javax.swing.JButton btnListadoPorCurso;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
