/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

import interfazEmpleado.Eliminar;
import interfazEmpleado.ConsultaEstado;
import interfazEmpleado.Registro;
import interfazEmpleado.AsignarCurso;
import interfazEmpleado.Modificar;
/**
 *
 * @author jesus
 */
public class MenuEmpleado extends javax.swing.JInternalFrame {

    /**
     * Creates new form menuEmpleado
     */
    public MenuEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRegistrarEmpleado = new javax.swing.JButton();
        btnAsignarCurso = new javax.swing.JButton();
        btnConsultarEstado = new javax.swing.JButton();
        btnModificarDatos = new javax.swing.JButton();
        btnBorrarEmpleado = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(802, 340));
        setMinimumSize(new java.awt.Dimension(802, 340));
        setPreferredSize(new java.awt.Dimension(802, 340));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jPanel1.setMaximumSize(new java.awt.Dimension(802, 340));
        jPanel1.setMinimumSize(new java.awt.Dimension(802, 340));
        jPanel1.setPreferredSize(new java.awt.Dimension(802, 340));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrarEmpleado.setText("Aceptar");
        btnRegistrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 92, -1, -1));

        btnAsignarCurso.setText("Aceptar");
        btnAsignarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarCursoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAsignarCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 92, -1, -1));

        btnConsultarEstado.setText("Aceptar");
        btnConsultarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarEstadoActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultarEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(642, 92, -1, -1));

        btnModificarDatos.setText("Aceptar");
        btnModificarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarDatosActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 198, -1, -1));

        btnBorrarEmpleado.setText("Aceptar");
        btnBorrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorrarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 198, -1, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, -1, -1));

        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Borrar Empleado", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 170, 80));

        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrar Empleado", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 170, 80));

        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Asignar Curso", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 170, 80));

        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consulatr Estado", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 170, 80));

        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modificar Datos", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 170, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAsignarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarCursoActionPerformed

        this.setVisible(false);
        
        AsignarCurso curso=new AsignarCurso();
        Principal.panelPrincipal.add(curso);
        curso.setVisible(true);

    }//GEN-LAST:event_btnAsignarCursoActionPerformed

    private void btnRegistrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEmpleadoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
        Registro empleado= new Registro();
        Principal.panelPrincipal.add(empleado);
        empleado.setVisible(true);
        
    }//GEN-LAST:event_btnRegistrarEmpleadoActionPerformed

    private void btnConsultarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarEstadoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
        ConsultaEstado empleado=new ConsultaEstado();
        Principal.panelPrincipal.add(empleado);
        empleado.setVisible(true);
    }//GEN-LAST:event_btnConsultarEstadoActionPerformed

    private void btnModificarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarDatosActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        
        Modificar empleado= new Modificar();
        Principal.panelPrincipal.add(empleado);
        empleado.setVisible(true);
    }//GEN-LAST:event_btnModificarDatosActionPerformed

    private void btnBorrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarEmpleadoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
        Eliminar empleado=new Eliminar();
        Principal.panelPrincipal.add(empleado);
        empleado.setVisible(true);
    }//GEN-LAST:event_btnBorrarEmpleadoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        Principal.activarPanel();
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignarCurso;
    private javax.swing.JButton btnBorrarEmpleado;
    private javax.swing.JButton btnConsultarEstado;
    private javax.swing.JButton btnModificarDatos;
    private javax.swing.JButton btnRegistrarEmpleado;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
