/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author jesus
 */
public class menuListado extends javax.swing.JInternalFrame {

    /**
     * Creates new form menuListado
     */
    public menuListado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnListadoPorCurso = new javax.swing.JButton();
        btnListadoPorCicloLectivo = new javax.swing.JButton();
        btnListadoDeEgresado = new javax.swing.JButton();
        btnListadoDeudores = new javax.swing.JButton();
        btnListadoAbandono = new javax.swing.JButton();
        btnListadoGeneral = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        btnListadoPorCurso.setText("Aceptar");

        btnListadoPorCicloLectivo.setText("Aceptar");

        btnListadoDeEgresado.setText("Aceptar");

        btnListadoDeudores.setText("Aceptar");

        btnListadoAbandono.setText("Aceptar");

        btnListadoGeneral.setText("Aceptar");

        btnSalir.setText("Salir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(43, 43, 43))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnListadoDeudores)
                    .addComponent(btnListadoPorCurso))
                .addGap(169, 169, 169)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnListadoPorCicloLectivo)
                        .addGap(183, 183, 183)
                        .addComponent(btnListadoDeEgresado))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnListadoAbandono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnListadoGeneral)))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListadoPorCurso)
                    .addComponent(btnListadoPorCicloLectivo)
                    .addComponent(btnListadoDeEgresado))
                .addGap(103, 103, 103)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListadoDeudores)
                    .addComponent(btnListadoAbandono)
                    .addComponent(btnListadoGeneral))
                .addGap(71, 71, 71)
                .addComponent(btnSalir)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListadoAbandono;
    private javax.swing.JButton btnListadoDeEgresado;
    private javax.swing.JButton btnListadoDeudores;
    private javax.swing.JButton btnListadoGeneral;
    private javax.swing.JButton btnListadoPorCicloLectivo;
    private javax.swing.JButton btnListadoPorCurso;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
