/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author jesus
 */
public class menuAlumno extends javax.swing.JInternalFrame {

    /**
     * Creates new form menuAlumno
     */
    public menuAlumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnInscribir = new javax.swing.JButton();
        btnPagos = new javax.swing.JButton();
        btnModificarDatos = new javax.swing.JButton();
        btnBajaAlumno = new javax.swing.JButton();
        btnMotivoBaja = new javax.swing.JButton();
        btnConsultarEstado = new javax.swing.JButton();
        btnConsultarPagos = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInscribir.setText("Aceptar");
        jPanel1.add(btnInscribir, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        btnPagos.setText("Aceptar");
        jPanel1.add(btnPagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        btnModificarDatos.setText("Aceptar");
        btnModificarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarDatosActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, -1));

        btnBajaAlumno.setText("Aceptar");
        jPanel1.add(btnBajaAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, -1, -1));

        btnMotivoBaja.setText("Aceptar");
        jPanel1.add(btnMotivoBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        btnConsultarEstado.setText("Aceptar");
        jPanel1.add(btnConsultarEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, -1));

        btnConsultarPagos.setText("Aceptar");
        jPanel1.add(btnConsultarPagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, -1, -1));

        btnSalir.setText("Salir");
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 330, -1, -1));

        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consultar Pago Alumno", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 170, 70));

        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inscribir Alumno", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 160, 70));

        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Efectuar Pago", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 160, 70));

        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modificar Alumno", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 160, 70));

        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dar de Baja Alumno", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 160, 70));

        jLabel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Motivos de Baja Alumno", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 170, 70));

        jLabel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consultar Estado Alumno", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 180, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 879, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarDatosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBajaAlumno;
    private javax.swing.JButton btnConsultarEstado;
    private javax.swing.JButton btnConsultarPagos;
    private javax.swing.JButton btnInscribir;
    private javax.swing.JButton btnModificarDatos;
    private javax.swing.JButton btnMotivoBaja;
    private javax.swing.JButton btnPagos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
