/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazAlumno;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.table.DefaultTableModel;
import menu.Principal;

/**
 *
 * @author Nero
 */
public class SelctModificar extends javax.swing.JInternalFrame {
    
    PreparedStatement ps;
    ResultSet rs;
    Connection conexion = clases.Conectar.conexion();
    int id;
    public static int idsel;
    String sel;

    public SelctModificar() {
        initComponents();
//        selec.setVisible(false);
        btnmodi.setEnabled(false);
        try {
            Connection conexion = clases.Conectar.conexion();
            
            rs = clases.TablaEliminar.Creartablacompl(conexion);
            DefaultTableModel mod = clases.TablaEliminar.AsignarModelo(rs);
            
            tablamodificar.setModel(mod);
            
            conexion.close();
        } catch (Exception e) {
            System.err.print(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtdni = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnbuscar = new javax.swing.JButton();
        selec = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btncancelar = new javax.swing.JButton();
        btnmodi = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablamodificar = new javax.swing.JTable();
        jTextField6 = new javax.swing.JTextField();

        jPanel2.setBackground(new java.awt.Color(38, 86, 186));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seleccione al alunmo");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, -1, -1));
        jPanel2.add(txtdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 12, 120, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("D.N.I");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 18, -1, -1));

        btnbuscar.setBackground(new java.awt.Color(0, 0, 0));
        btnbuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        jPanel2.add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 13, 142, -1));

        selec.setForeground(new java.awt.Color(255, 255, 255));
        selec.setText("jLabel3");
        jPanel2.add(selec, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncancelar.setBackground(new java.awt.Color(38, 86, 186));
        btncancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, 103, -1));

        btnmodi.setBackground(new java.awt.Color(38, 86, 186));
        btnmodi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnmodi.setText("Modificar");
        btnmodi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodiActionPerformed(evt);
            }
        });
        jPanel1.add(btnmodi, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 210, 103, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cursos Inscriptos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablamodificar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Título 3", "Título 4", "Título 5", "Título 6", "Título 7", "Título 8", "Título 9", "Título 10", "Título 11", "Título 12"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablamodificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablamodificarMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablamodificar);

        jScrollPane3.setViewportView(jScrollPane2);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 640, 290));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 330));

        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("FOTO");
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 12, 172, 161));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        
        Principal.activarPanel();
        dispose();        
        
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnmodiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodiActionPerformed
        selec.setText(sel);
        idsel = Integer.parseInt(sel);
        
        this.setVisible(false);
        Principal.desactivarPanel();
        Modificar modificar = null;
        try {
            modificar = new Modificar();
        } catch (SQLException ex) {
            Logger.getLogger(SelctModificar.class.getName()).log(Level.SEVERE, null, ex);
        }
        Principal.panelPrincipal.add(modificar);
        modificar.setVisible(true);
    }//GEN-LAST:event_btnmodiActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        String aux = txtdni.getText();
        if (txtdni.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "falta ingresar el Legajo para buscar", "error...", ERROR_MESSAGE);
        } else {
            try {
                Connection conexion = clases.Conectar.conexion();
                rs = clases.TablaEliminar.buscarDNI(conexion, txtdni.getText());
                DefaultTableModel mod = clases.TablaEliminar.AsignarModelo(rs);
                tablamodificar.setModel(mod);
                
                conexion.close();
            } catch (Exception e) {
                System.err.print(e);
            }
          
        }
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void tablamodificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablamodificarMouseClicked
       int fila = tablamodificar.getSelectedRow();
        int id2 = tablamodificar.getColumnModel().getColumnIndex("Legajo");
        sel = String.valueOf(tablamodificar.getValueAt(fila, id2));
        selec.setText(sel);
        idsel = Integer.parseInt(sel);
        btnmodi.setEnabled(true);
    }//GEN-LAST:event_tablamodificarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnmodi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel selec;
    private javax.swing.JTable tablamodificar;
    private javax.swing.JTextField txtdni;
    // End of variables declaration//GEN-END:variables
}
